[package]
name = "basic_perceptron"
version = "0.1.0"
authors = ["crispycookies <crispycookies@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6"
num-traits = "0.2"
